channels:
- conda-forge
dependencies:
- python=3.8.9
- pip<=23.0.1
- pip:
  - mlflow
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - lightgbm==3.3.5
  - matplotlib==3.5.3
  - psutil==5.9.4
  - scikit-learn==1.1.2
name: mlflow-env
